# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  mainPart = "/dev/disk/by-uuid/88c5f974-bde5-4b5b-8f1a-085e625bfb78";
  bootPart = "/dev/disk/by-uuid/DEA8-6959";
  resumeOffset = "72843264";
in {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    # Bootloader
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    initrd = {
      availableKernelModules =
        [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];

    # Swapfile hibernate
    resumeDevice = "${mainPart}";
    kernelParams = [ "resume_offset=${resumeOffset}" ];
  };

  fileSystems = {
    "/" = {
      device = "${mainPart}";
      fsType = "ext4";
    };

    "/boot" = {
      device = "${bootPart}";
      fsType = "vfat";
    };
  };

  swapDevices = [{
    device = "/swapfile";
    size = 16 * 1024;
  }];

  # swapDevices = [{
  #   device = "/dev/disk/by-uuid/72d97190-ce60-442e-a210-5efe0cdcd10f";
  # }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
