# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  #boot.resumeDevice = "/dev/mapper/cryptswap";  # for hibernation
  #  boot.initrd.luks.devices = {
  #  cryptroot = { device = "/dev/disk/by-partlabel/luksRoot"; tpm2 = true; fido2 = true; };
  #  cryptswap = { device = "/dev/disk/by-partlabel/luksSwap"; tpm2 = true; fido2 = true; };
  #};

  #boot.resumeDevice = "/dev/mapper/cryptswap"; # hibernation
  security.tpm2.enable = true;

  #fileSystems = {
  #  "/" = { device = "/dev/mapper/cryptroot"; fsType = "btrfs"; options = [ "subvol=@root" "compress=zstd" "noatime" ]; };
  #  "/home" = { device = "/dev/mapper/cryptroot"; fsType = "btrfs"; options = [ "subvol=@home" "compress=zstd" "noatime" ]; };
  #  "/boot" = { device = "/dev/disk/by-partlabel/esp"; fsType = "vfat"; };
  #};

  #swapDevices = [ { device = "/dev/mapper/cryptswap"; } ];
}
