#+title: Installation
* About the Installation
All of my computers use a 512MB EFI partition and a ext4 partition with a swapfile that's double the RAM of my machines (with the exception of my desktop, since the ram is quite large, its swapfile is equal to that of the machine).

Home-manager is configured in [[https://nix-community.github.io/home-manager/index.html#id-1.2][standalone mode]], so when NixOS is rebuilt Home-manager would then also need to be rebuilt manually with =home-manager switch=.

* First-time NixOS Install
1. Download a NixOS ISO or create custom one with nix experimental features and Nvidia drivers installed by following the instructions over under [[file:tips.org][Tips]]; then boot into the ISO's live image environment
2. Download the repo onto the live image copy of NixOS.
3. Open the terminal and enter the repo directory.
4. *IMPORTANT*: For modules that include =evaluation secrets= (secrets that used during the flake's evaluation; which *DOES NOT* include the secrets from =sops-nix=), you will not be able to directly use said modules without removing them along with git-crypt and change them to be your own. See more under  [[file:tips.org][Tips]]. For your own version of the repo, you simply transfer the GPG private key used to encrypt the secrets onto the machine you are installing to and run the command =git-crypt unlock=.
5. Run =nix-shell= or =nix develop= to enter environment with all necessary packages to build the config properly
   - =nix-shell= is available on any version of nix. However, in order to use =nix develop=, you must have nix v2.4+, git, and have enabled the =flakes= and =nix-command= experimental features. If you are using the custom ISO as stated previously, you can use =nix develop= without having to do anything additional as the configs already have the needed configurations and dependencies
6. Follow the instructions over in [[file:partitioning.org][Partitioning]]!
7. Run =nixos-generate-config --show-hardware-config --root /mnt= to create a base configuration file that the installer provides.
8. Add any of the additional kernel modules as exactly as they appear into the =hosts/HOSTNAME/hardware/hardware-configuration= file.
9. Change the =FLAKE= variable located under =home/USERNAME/global/default.nix=. Some dotfiles are sym-links that aren't located on nix store and not having the repo in the location that the variable specifies will cause the links to break. This would in turn result in some apps malfunctioning or not have your settings.
10. Run =nixos-install --flake .#HOSTNAME --root /mnt= to install NixOS with the configuration
11. If you did not set a user password, make sure you use =nixos-enter= to set a password for the user!
12. Move repo into the folder located on /mnt that matches your =FLAKE= environment variable
13. Restart and the system will boot up into NixOS!

* Post Install
Once your system boots, check out [[file:post-install.org][Post Install]] for instructions for system and application setup steps that can only be done once the system is installed and booted.
