#+title: Installation
* About the Installation
All of my computers use a 512MB EFI partition and a ext4 partition with a swapfile that's double the RAM of my machines (with the exception of my desktop, since the ram is quite large, its swapfile is equal to that of the machine).

Home-manager is configured in [[https://nix-community.github.io/home-manager/index.html#id-1.2][standalone mode]], so when NixOS is rebuilt Home-manager would then also need to be rebuilt manually with =home-manager switch=.

* First-time NixOS Install
1. Download the repo onto an live image copy of NixOS.
2. Open the terminal and enter the repo directory.
3. Run =nix-shell= or =nix develop= to enter environment with all necessary packages to build the config properly
   - =nix-shell= can be used on any version of nix. However, in order to use =nix develop=, you must have nix v2.4+, git, and have enabled the =flakes= and =nix-command= experimental features.
4. Follow the instructions over in the [[file:partitioning.org][Partitioning]] file!
5. Run =nixos-generate-config --show-hardware-config --root /mnt= to create a base configuration file that the installer provides.
6. Add any of the additional kernel modules as exactly as they appear into the =hosts/HOSTNAME/hardware-configuration= file.
7. Change the =FLAKE= variable located under =home/USERNAME/global/default.nix=. Some dotfiles are sym-links that aren't located on nix store and not having the repo in the location that the variable specifies will cause the links to break. This would in turn result in some apps malfunctioning or not have your settings.
8. Run =nixos-install --flake .#HOSTNAME --root /mnt= to install NixOS with the configuration
9. If you did not set a user password, make sure you use =nixos-enter= to set a password for the user!
10. Move repo into the folder located on /mnt that matches your =FLAKE= environment variable
11. Restart and the system will boot up into NixOS!

* Post Install
Once your system is booted, check out the [[file:post-install.org][Post Install]] file for instructions for system and application setup steps that can only be done once the system is installed and booted.
