#+title: =Partitioning and Mounting=

Based on [[https://github.com/Baitinq/nixos-config/tree/master][Baitinq's nix-config]]! My configuration has extra helper scripts for partitioning and mounting the system.

These scripts live in [hosts/HOSTNAME/disks.nix] (which must customized to fit your specific configuration).

* Creating the Partitions
Execute =nix run .#nixosConfigurations.$HOSTNAME.config.disks-create= to create the disks. Please be warned that this command will destroy everything on the disk so make sure you correctly defined the device in the configs and backed up everything!!!

* Formatting the Partitions
Execute =nix run .#nixosConfigurations.$HOSTNAME.config.disks-format= to format the filesystems on the newly created partitions

* Mounting the Partitions
Execute =nix run .#nixosConfigurations.$HOSTNAME.config.disks-mount= to mount all of the newly created partitions to the live installer

* Get Resume Offset for swapfiles
Execute =nix run .#nixosConfigurations.$HOSTNAME.config.get-resume-offset= to calculate what the =resume-offset= value should be for the current system. This is required since I'm using swapfiles; the system needs to know where the swap header is on the system's disk. This command can only be ran *AFTER* the installation is complete and the system booted, as the swapfile isn't mounted nor exist in the live image. Once it's ran, you take this value and put it in the =hosts/HOSTNAME/hardware-configuration.nix= file under the =resumeOffset= variable.
