# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  mainPart = "/dev/disk/by-uuid/f402bc6a-38cc-402a-82f6-3f8fdd6e4c49";
  bootPart = "/dev/disk/by-uuid/9B30-918B";
  resumeOffset = "12550144";
in {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    # Bootloader
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    initrd = {
      availableKernelModules =
        [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
      kernelModules = [ "ideapad_laptop" ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    # Swapfile hibernate
    resumeDevice = "${mainPart}";
    # mem_sleep and pcie_aspm policy changes provide much better energy savings
    kernelParams = [
      "resume_offset=${resumeOffset}"
      #"mem_sleep_default=deep"
      #"pcie_aspm.policy=powersupersave"
    ];
  };

  fileSystems = {
    "/" = {
      device = "${mainPart}";
      fsType = "ext4";
    };

    "/boot" = {
      device = "${bootPart}";
      fsType = "vfat";
    };
  };

  swapDevices = [{
    device = "/swapfile";
    size = 16 * 1024;
  }];

  # swapDevices = [{
  #   device = "/dev/disk/by-uuid/57c9756d-3deb-4225-bd37-2e34010586aa";
  # }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
